### ISSUE TITLE
Select without using jdbc(datasource) function

### ISSUE THREAD

**Issue by ramazanpolat** [zhicwu/clickhouse-datasource-bridge#1]
In READ.ME, there is this:

>You can put query parameters like max_rows either in config or in the query.

```sql
-- get the first 10 rows(based on above configuration)
select * from('ch', '', 'test-query')
-- get a specific row
select * 
from('ch?max_rows=3&offset=2', '',
    'select * from test-table order by column1 desc')
```

In the query, there is no jdbc table function after the `from` keyword, is this a typo?

**Comment by zhicwu** [comment]
Yep, typo :)))

**Comment by ramazanpolat** [comment]
I didn't test this yet but having these features will be great. Will try it asap.
